### ISSUE TITLE
Class Css rules not recognized

### ISSUE THREAD

**Issue by TheRealMrCrowley** [DevMountain/precourseCamp#15]
#### Browser Information

- Browser Name, Version: 
- Operating System: 
- Mobile, Desktop, or Tablet: 
#### Your Code

``` js
// If relevant, paste all of your challenge code in here

```

**Comment by TheRealMrCrowley** [comment]
All the info is gone... 

Code:

<style>
  h2 {color: #00F;}
</style>
<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>



Android Chrome 52

**Comment by TheRealMrCrowley** [comment]
<style>
      h2 {color: red;}
    </style>
    <h2>CatPhotoApp</h2>

    <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by TheRealMrCrowley** [comment]
Dammit I can't get this right. The code is:

    <style>
      .red-text {color: red;}
    </style>
    <h2 class="red-text">CatPhotoApp</h2>

    <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by TheRealMrCrowley** [comment]
The challenge is change text color with css class

**Comment by Kedirech** [comment]
Hmm, it looks like your code is correct.  It's not passing when you run the tests? What device/broswer are you working on?

**Comment by TheRealMrCrowley** [comment]
My code is correct. It is not passing with the error that the h2 should've been red. Creating a second rule directly on the h2 let me move on to the next challenge.

The problem is with Android Chrome 52

Samps 
Web Master 
Cottage Skis 
702-375-8059 




-------- Original Message --------
