### ISSUE TITLE
what am i doing wrong here ? 

### ISSUE THREAD

**Issue by Hosway** [DevMountain/precourseCamp#23]
Challenge [Test Scores](https://precourse.devmountain.com/challenges/test-scores) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function scoreTest(correct, questions) {
  var percent;
  // Only change code below this line
  percent = 20 / 25 * 100;
  
  // Only change code above this line
  return percent;
 
}

// Change the inputs below to test your code
scoreTest(47, 50);
scoreTest(16, 20);
scoreTest(97, 100);
scoreTest(1, 50);
```

**Comment by Devbot0716** [comment]
I see what I did wrong. It should be:

totalPrice = price * quantity * salesTax + price * quantity;

had to get the salesTax figured out before I added the price*quantity
